export function helpContent(): string {
  return `<p>Start small: harvest, stock a shelf, serve a customer, then collect your cash. The on-screen arrow guides your first delivery.</p>
  <details open><summary>Moving and serving</summary><p>Use WASD, arrows, the joystick, or drag the world. Hold Shift or Sprint for a short burst. Gold footprint circles mark places to stand; green means you are close enough. Items transfer automatically.</p><p>Customers borrow a cart, use the front door and shop. Stand beside checkout to serve them until you hire a cashier. Each purchase earns 5 XP plus 2 XP per item. Walk into the cash circle to bank the payment, then step away before collecting again. Helpers never bank money.</p></details>
  <details><summary>Growing a market that works</summary><p>Manage → Store recommends upgrades for your current bottleneck. New departments require money, paid orders and player levels. Existing purchases stay owned. Shelf upgrades add rows; carts add customer capacity. Empty shelves need better supply before more marketing.</p><p>Manage → Goals has five business chapters, claimable milestones, optional contracts and regulars. Contracts never expire and can be cancelled without a penalty. Complete two or five to earn new shop signs. Regulars reward every fifth paid visit that includes their favorite product.</p></details>
  <details><summary>Helpers and production</summary><p>In Manage → Staff, choose balanced work, urgent shelves, processors or a favorite product for each helper. Preferences fall back to other useful jobs. Increase carrying capacity and speed as demand grows.</p><p>In Manage → Machines, choose shelf-first to reserve raw stock, processing-first to favor finished goods, or pause new batches. Quick mode makes whatever is available; full-batch mode waits for the machine’s entire upgraded batch. A paused machine finishes its current batch.</p><p>Supply tomatoes to the cannery, coffee beans to the grinder, milk to the dairy kitchen, or corn to the grill. The accountant audits completed business: 2 XP per tier for every five paid orders, never idle XP.</p></details>
  <details><summary>Rush hours, queues and delivery</summary><p>Manage → Goals offers optional 90-second rush hours: Gentle (6 orders, 75 XP), Busy (12, 150 XP), and Festival (20, 250 XP). Each difficulty requires enough carts, experience and some shelf stock. New attempts unlock after 60 seconds. Failure costs no money.</p><p>Small faces appear only for an empty shelf, a long payment wait or a completed purchase. Customers leave after two minutes of waiting, returning their goods.</p><p>After 10 paid orders you may buy drive-through service. Carry its requested items to the window one at a time, then stay for payment. Its runner and cashier are separate hires. Its cash must be collected too.</p></details>
  <details><summary>Cash and a fair chance to catch thieves</summary><p>Cash piles have no storage limit and never close a register. After three minutes of neglect a thief may approach, followed by a 12-second stealing warning. They can take 25% of a pile, capped at $250. Sprint close enough to put them inside your visible net circle and recover it. A helper guards them until police arrive; without a helper the net holds them.</p><p>Theft encounters freeze in every menu. The shop and rush timers continue by default. Settings → Safe pause freezes the whole game in menus. Hidden tabs and closed games do not simulate offline earnings.</p></details>
  <details><summary>Comfort and keeping your save</summary><p>Settings includes camera zoom, music and effects volume, plus a 30 FPS low-power mode that does not slow gameplay. On phones, use More for secondary controls.</p><p>Download backups before changing devices or clearing browser data. Imports show a preview and require confirmation, keeping a recovery copy. If online accounts are connected, the account screen offers manual cloud upload and restore with conflict protection. Guest play needs no account.</p></details>`;
}
